これできてる？
N3AttendanceManager/AttendanceApp pull request #5
Opened 2024-01-18 05:49 UTC by batapii

うおおおおおおおおおおおおおおおおおおおおおおお

2024-01-18 05:52 UTC, yuchan2215 requested changes
プレビュー作ったならプレビューのスクショをPRに添付しなさい😡😡😡（身内ノリ）

2024-01-18 05:52 UTC, yuchan2215 commented
うそこれドラフトかごめん

2024-01-18 05:55 UTC, yuchan2215 requested changes
プレビューパラメータの値が実態に沿ってない
→出席区分をもっと現実的なものに

プレビューされるデータを増やす
→もうちょいリアリティのある画面に

`PreviewSurface`でかこってね❤️

2024-01-18 06:17 UTC, batapii commented
どうやって増やすの

2024-01-18 06:47 UTC, batapii commented
どお

2024-01-24 01:34 UTC, yuchan2215 approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8244663)

2024-01-24 01:34 UTC, merged